### ISSUE TITLE
Can't find model 'vi_spacy_model'

### ISSUE THREAD

**Issue by anonymousz97** [trungtv/vi_spacy#4]
I can't load model vi_spacy_model. It said : 
OSError: [E050] Can't find model 'vi_spacy_model'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

**Comment by nhha1602** [comment]
Hi,
Let try following steps ...
pip3 install spacy==2.2.3 --user
pip3 install pyvi --user
pip3 install https://github.com/trungtv/vi_spacy/raw/master/packages/vi_spacy_model-0.2.1/dist/vi_spacy_model-0.2.1.tar.gz --user
python3 -m spacy link vi_spacy_model vi_spacy_model
python3 -m spacy info

**Comment by anonymousz97** [comment]
Thanks , it's work 👍
