### ISSUE TITLE
How can I remove underscore of output token.text ?

### ISSUE THREAD

**Issue by nhha1602** [trungtv/vi_spacy#5]
How can I remove underscore of output token.text ?

As below example, i got underscore in output of token.text. How to remove it by configure it?

Python 3.6.8 (default, Aug  7 2019, 17:28:10)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> nlp = spacy.load('vi_spacy_model')
>>> doc = nlp('Cộng đồng xử lý ngôn ngữ tự nhiên')
>>> for token in doc:
...     print(token.text, token.lemma_, token.pos_, token.tag_, token.dep_,
...             token.shape_, token.is_alpha, token.is_stop)
...
Cộng_đồng Cộng_đồng X N nsubj xxxxxxxxx False False
xử_lý xử_lý X V ROOT xxxxx False True
ngôn_ngữ ngôn_ngữ X N obj xxxxxxxx False False
tự_nhiên tự_nhiên X A compound xxxxxxxx False False
>>>

**Comment by trungtv** [comment]
Hello,
I haven't found a good way to implement this feature because using underscore is a defacto standard.
