### ISSUE TITLE
POS tagging not working

### ISSUE THREAD

**Issue by truongkhanhduy95** [trungtv/vi_spacy#6]
Seem it always return 'X' for token.pos_, even with your example
`Cộng_đồng Cộng_đồng X N nsubj xxxxxxxxx False False
xử_lý xử_lý X V ROOT xxxxx False True
ngôn_ngữ ngôn_ngữ X N obj xxxxxxxx False False
tự_nhiên tự_nhiên X Nb compound xxxxxxxx False False`

**Comment by mayankchatteron1** [comment]
Yes, it is not working.

**Comment by trungtv** [comment]
It's actually token.tag_ according to universal dependency schema
