### ISSUE TITLE
can't load vi_spacy_model

### ISSUE THREAD

**Issue by trihdm95** [trungtv/vi_spacy#7]
chào Anh, e làm theo hướng dẫn nhưng khi chạy spacy validate thì nó không load dc vi_spacy_model? Không biết vì s ạ ?

![image](https://user-images.githubusercontent.com/33822871/87408226-5dcf2900-c5ed-11ea-9151-4dcf140607f4.png)

**Comment by huybik** [comment]
Do model không tương thích với spacy bản mới nhất. Bạn downgrade spacy 2.2 sẽ dùng được (spacy 2.1 không tương thích python 3.8). Nếu anh Trung rãnh train giúp lại model cho spacy mới, vì em không có data train nên không giúp được ạ :D

**Comment by votuandi** [comment]
> chào Anh, e làm theo hướng dẫn nhưng khi chạy spacy validate thì nó không load dc vi_spacy_model? Không biết vì s ạ ?
> 
> ![image](https://user-images.githubusercontent.com/33822871/87408226-5dcf2900-c5ed-11ea-9151-4dcf140607f4.png)

Bạn cho mình hỏi, khi mình làm theo hướng dẫn nhưng khi chạy link thì nó báo không được ạ
![image](https://user-images.githubusercontent.com/41782079/93160202-0c046580-f73a-11ea-9c2f-502a5475ad09.png)

**Comment by Ngo-Tuan-Anh** [comment]
> Do model không tương thích với spacy bản mới nhất. Bạn downgrade spacy 2.2 sẽ dùng được (spacy 2.1 không tương thích python 3.8). Nếu anh Trung rãnh train giúp lại model cho spacy mới, vì em không có data train nên không giúp được ạ :D

Cám ơn bạn. Mình downgrade 2.3.2 xuống 2.2.1 mới load được model

**Comment by trungtv** [comment]
Hello,
Vi_spacy for Spacy 3.x is here https://gitlab.com/trungtv/vi_spacy
