### ISSUE TITLE
Can't locate model data

### ISSUE THREAD

**Issue by votuandi** [trungtv/vi_spacy#8]
Mình chạy lệnh pip install https://github.com/trungtv/vi_spacy/raw/master/packages/vi_spacy_model-0.2.1/dist/vi_spacy_model-0.2.1.tar.gz 
Sau đó link vào spacy nhưng báo không locate được model.
Mọi người giúp mình với ạ
![image](https://user-images.githubusercontent.com/41782079/93159922-7d8fe400-f739-11ea-8b83-849556df892a.png)

**Comment by Ngo-Tuan-Anh** [comment]
Hồi trước mình cài 1 lần là gọi được vi-spacy-model. Bây giờ, mình cũng gặp vấn đề này mà không biết giải quyết thế nào. Gặp lỗi cũng tương tự
`>>> import spacy
>>> nlp = spacy.load('vi_spacy_model')
....................................................................
OSError: [E050] Can't find model 'vi_spacy_model.vectors'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.`

**Comment by trungtv** [comment]
If it is due to 3.x version then I am training a new one.

**Comment by trungtv** [comment]
Hello,
Vi_spacy for Spacy 3.x is here https://gitlab.com/trungtv/vi_spacy
